# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5542a49340b20c1cd38340155008a511ec8eda97f17b7e62eefc395747a4a535f58dbdb99ea01a5aedcb466803fa7f50929f74f2e3208cfccd390736b3a35ff

test:
  secret_key_base: 00049784139851d4d06877226cc1b40ec98eaa92e5bc19d811576b89552a60cce9b102110d446e2d8d6c2a47991102666b1790f9f5f486393bcafc81724a93b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
